repos:
  # --- Python formatter: Black ---
  - repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
      - id: black
        language_version: python3.10

  # --- Python linter & fixer: Ruff ---
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.14.1
    hooks:
      - id: ruff
        args: ["--fix"]

  # --- Import sorter: isort ---
  - repo: https://github.com/PyCQA/isort
    rev: 7.0.0
    hooks:
      - id: isort

  # --- Markdown formatter: Prettier ---
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        name: prettier-markdown
        files: \.(md|markdown|mdown|mkdn|mkd)$
        args: ["--write"]
